---
- name: Install Zabbix agent2 and plugins
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-mongodb
      - zabbix-agent2-plugin-mssql
      - zabbix-agent2-plugin-postgresql
    state: present
    update_cache: yes

- name: Deploy Zabbix agent2 configuration file
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Zabbix Agent2

- name: Start and enable Zabbix Agent2 service
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

# Optionally remove Apache task from here
